name: Continous Integration
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install pipenv
      run: python -m pip install --upgrade pipenv
    
    - name: Install dependencies
      run: pipenv install --dev --skip-lock

    - name: Install mypy stubs
      run: mypy --install-types

    - name: Lint using pylint
      run: pipenv run lint

    - name: Perform static code analysis
      run: pipenv run mypy