name: Continous Integration
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Run Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry_version: 1.1.12

    - name: Install dependencies
      run: poetry install

    - name: Run unit tests
      run: bash ./scripts/test.sh

    - name: Lint using pylint
      run: bash ./scripts/lint.sh

    - name: Perform static code analysis
      run: bash ./scripts/static.sh