name: Continous Integration
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Run Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.12

    - name: Install dependencies
      run: poetry install

    - name: Run unit tests
      run: make test

    - name: Lint using pylint
      run: make lint

    - name: Check code style using Black
      run: make style

    - name: Perform static code analysis
      run: make static