name: Continous Integration
on: [push]

jobs:
  quality:
    name: Assure code quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        job: [lint, test, style, static]

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Run Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12

      - name: Install dependencies
        run: poetry install

      - name: Run "${{ matrix.job }}"
        run: make ${{ matrix.job }}